### ISSUE TITLE
Changing server in settings causes app crash

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube-viewer#100]
In current version 0.2.1 there is a severe regression causing the viewer app to crash, if users change the server in the settings window.

![image](https://user-images.githubusercontent.com/206773/68705402-4affe280-058e-11ea-99cd-06da5fc00f8f.png)

Caused by color bar legend added to OpenLayers 6.1.1 map.

**Comment by forman** [comment]
Weird, failed to reproduce this on my office computer - same OS, same yarn.lock...

**Comment by forman** [comment]
@hdzierz, @AliceBalfanz, can you please try to reproduce this issue too?

**Comment by AliceBalfanz** [comment]
When changing to https://cyanoalert.brockmann-consult.com/api/latest it works perfectly fine, but when I change the server to https://xcube2.dcs4cop.eu/dcs4cop-dev/api/latest I experience a similar issue. 

![Screenshot from 2019-11-19 12-10-55](https://user-images.githubusercontent.com/23457217/69144254-2b574580-0acb-11ea-9725-f34a3cb3e98d.png)

**Comment by digitaltopo** [comment]
Having the same issue with the demo viewer at https://xcube-viewer.s3.eu-central-1.amazonaws.com/index.html

Tried with several servers:

- https://xcube2.dcs4cop.eu/dcs4cop-dev/api/latest/
- https://cyanoalert.brockmann-consult.com/api/latest/

**Comment by forman** [comment]
The issue seems to be fixed, as we no longer use the PWA cache. 
If it persists, please feel free to reopen.
