### ISSUE TITLE
Failed to compile - error in ./src/components/ol/types.ts

### ISSUE THREAD

**Issue by joaofelipecsantos** [dcs4cop/xcube-viewer#102]
Machine: Linux, Ubuntu 18.04
Last xcube update: 22/11/2019 @ 11:30am
Last xcube-viewer update: 22/11/2019 @ 11:30am

**Steps for the issue**:
- xcube-viewer was working before the update.
- I tried to update the xcube-viewer and I had an error message about yarn.lock and package.json.
- Was necessary to delete the yarn.lock and package.json from the xcube-viewer folder before update the xcube-viewer.
- After delete, the xcube-viewer updated correctly and created new yarn.lock and package.json files.
- I run the server ('successfully loaded')
- I run the viewer (command: `HOST=localhost yarn run start`)
- Error message:
**`Failed to compile.
./src/components/ol/types.ts
Module not found: Can't resolve 'ol/Feature' in '/home/jcardoso/xcube-viewer/src/components/ol'`**
- Same message in the browser (Firefox)
![ticket_04](https://user-images.githubusercontent.com/32440152/69420336-c98f1980-0d1e-11ea-87e1-638968f5bc63.png)

**Expectation**:
- See the data in the browser.

**Possibility**:
Should I reinstall the xcube-viewer?

**Comment by AliceBalfanz** [comment]
Hi Joao, could you please try `yarn install` before executing `yarn run start` ? This usually solves the issue for me.

**Comment by joaofelipecsantos** [comment]
Yes, it works.
Thank you very much.
