### ISSUE TITLE
https-support for xcube viewer

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#110]
Niklas asked me to add this issue: 

Since CyanoAlert are about to support user login in the xcube viewer the best practice is to use https instead of http. The BC web server hosting viewer.cyanoalert.com now supports https, in other words it’s possible to browse to both http://viewer.cyanoalert.com and https://viewer.cyanoalert.com. Later on we can force https if we want to.

However the https://viewer.cyanoalert.com needs to be checked before claiming full https-support. One thing is to look into is the ‘mixed content’ warning in Firefox indicating insecure images from http://cyanoalert.brockmann-consult.com.

**Comment by tiagoams** [comment]
Is this the same as https://github.com/dcs4cop/xcube/issues/302?
If the problem resides with xcube-viewer then maybe 302 could be closed.

**Comment by forman** [comment]
Fixed long time ago.
