### ISSUE TITLE
No units shown in on the fly created dataset

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#113]
Units of variables do not show up in a created time series whenever the dataset is created on the fly. 
To reproduce:
1. go to http://viewer.cyanoalert.com/
2. select a dataset which has irregular time coverage and create a time series for a variable at a selected location
![image](https://user-images.githubusercontent.com/23457217/72972865-7a23a300-3dcc-11ea-885d-b9f1c5ce114d.png)

3. select a on the fly resampled dataset with daily mean and create the time series for the same variable - the units will not show up 
![image](https://user-images.githubusercontent.com/23457217/72973122-f28a6400-3dcc-11ea-9f2c-baa91820759f.png)

**Comment by forman** [comment]
This is not a viewer issue but a configuration problem of an individual xcube server. Please adapt the configuration's Python cube function so that variable attributes (such as units) are retained.

**Comment by AliceBalfanz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adjust Server Config to show units of on the fly resampled datasets](https://trello.com/c/MVnj2U4U/101-adjust-server-config-to-show-units-of-on-the-fly-resampled-datasets)

**Comment by forman** [comment]
Fixed in server configs.
