### ISSUE TITLE
Info space for dataset description

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#114]
It would be nice to be able to access some information about datasets in the viewer in order to know how it was produced, what the abbreviations in the dataset titles mean and to give some general info about the xcube dataset visualized in the viewer. 

This could be solved by an info button next to each xcube dataset which is selectable in the drop down menu of the datasets which then will show the information about the selected dataset.

**Comment by forman** [comment]
When we discussed this feature, the CyanoAlert team agreed, that this "info space" should apply to any selected items in the UI, datasets, variables, place groups, places.

See https://github.com/dcs4cop/xcube-viewer/issues/28

**Comment by forman** [comment]
**Idea:**

Let xcube server provide an optional template for individual datasets, variables, places etc. This will be used by xcube viewer to render the info cards. If not available, a default template will be used that will simply render dataset/variable metadata attributes or place (feature) properties. It should be possible to compose templates from others or extend others. 

Maybe there is a library out there for this purpose?
