### ISSUE TITLE
Strange connection of lines at first-time timeseries generation

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#117]
When plotting a time series for the first time for a certain location, the connecting lines of the points in the graph go a bit crazy, connecting not only points which are next in time. 

![image](https://user-images.githubusercontent.com/23457217/73158924-8fa70e80-40e5-11ea-8007-9e252d8391f3.png)

![image](https://user-images.githubusercontent.com/23457217/73158940-9c2b6700-40e5-11ea-965f-38415e8aeb93.png)

However, when removing the time-series and requesting it for the same location a second time everything is fine. 

Is this a viewer or rather a server issue? 

![image](https://user-images.githubusercontent.com/23457217/73158972-ae0d0a00-40e5-11ea-85a6-e08fa8718216.png)

**Comment by forman** [comment]
Weird.

**Comment by AliceBalfanz** [comment]
Have not seen this since the last released version. Reopen if issue returns.

**Comment by AliceBalfanz** [comment]
This issue has been reported again, so reopening. Noticed with cyanoalert production viewer by @jorritscholze
![image](https://user-images.githubusercontent.com/23457217/228840021-40fc9526-db44-4b64-a036-bc48c9b0e1c2.png)

**Comment by forman** [comment]
Pretty sure this is a poblem in the data.
