### ISSUE TITLE
timeseries graph lost when plotting new placemark (plot without line)

### ISSUE THREAD

**Issue by clebreton** [dcs4cop/xcube-viewer#141]
When plotting a timeseries without the lines (show data points only), as soon as a new timeseries is plotted in the same graph, the previous one disappears.
This does not happen (and appears back when switching to see the lines again) when the timeseries lines are there.

![image](https://user-images.githubusercontent.com/3809213/87637658-dabfe700-c742-11ea-81d7-ed3e2427089e.png)

![image](https://user-images.githubusercontent.com/3809213/87637722-f0cda780-c742-11ea-8705-7e63241a60ce.png)

**Comment by AliceBalfanz** [comment]
same as https://github.com/dcs4cop/xcube-viewer/issues/146, therefore closing
