### ISSUE TITLE
problem loading page after log out

### ISSUE THREAD

**Issue by clebreton** [dcs4cop/xcube-viewer#142]
after logging out, this page appears: 

![image](https://user-images.githubusercontent.com/3809213/87637946-430ec880-c743-11ea-8cfb-ad7d430ca214.png)

this is confusing for users

**Comment by forman** [comment]
Same as #132 ?

**Comment by AliceBalfanz** [comment]
> Same as #132 ?
Yes, I closed #132 now

**Comment by AliceBalfanz** [comment]
Furthermore, I have noticed, that when I logout, I get the same page as the screenshot above. When I then use the "go back" button of my browser, I am not logged in but still have access to all the data and can even create time series and all the things that should be blocked once I am not logged in anymore:

![image](https://user-images.githubusercontent.com/23457217/113867779-3d648180-97af-11eb-8525-b7e07f26511b.png)
