### ISSUE TITLE
Disappearing datapoints in time series when plotting second place with Firefox

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#146]
When plotting a time series for a second point of one variable, the first graph disappears when `Show data points only` is on with Firefox as browser. When `Show data points only` is off, at least the line still appears. Cache has been cleared beforehand. 

It has been tested with Chrome as well, there it works as expected. 

To reproduce:

1.    Open Chrome and Firefox (clear caches of both browsers) and follow the next steps in both internet browsers
2.    go to https://viewer.cyanoalert.com/ and log in
3.    Select Lake Mälaren cube
4.    From Places select some station
5.    generate a time series plot for the station
6.    Select another station and make a plot. 

Screenshot with  `Show data points only` off
![image](https://user-images.githubusercontent.com/23457217/96148473-95a97d80-0f08-11eb-95fa-7bbdceeadf94.png)

Screenshot with  `Show data points only` on
![image](https://user-images.githubusercontent.com/23457217/96148610-b5d93c80-0f08-11eb-8b9c-ae4916c9fd51.png)

**Comment by TonioF** [comment]
I have tested this with Chrome and got the same result.

**Comment by pont-us** [comment]
I get the "disappearing points" behaviour on the first graph with both Firefox 84.0.2 and Chrome 87.0.4280.141 (64-bit Ubuntu 20.04).

**Comment by forman** [comment]
After some lengthy investigations, I'm pretty sure our issue comes from an unsolved issue in `recharts` package: https://github.com/recharts/recharts/issues/1426

Trying a workaround now.

**Comment by SuperManEver** [comment]
@forman any ongoing pull request on solving this issue?

**Comment by AliceBalfanz** [comment]
hi @SuperManEver the xcube-viewer v0.4.5 does not have these issues anymore. Could you please update your xcube-viewer, and in case you still encouter this problem feel free to report on it and reopen the issue :)
