### ISSUE TITLE
Enhance xcube-viewer for use in containers 

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube-viewer#167]
Using xcube viewer from within a container has limitations w.r.t. to ingestion of configuration that specifies the server to use, the branding and optional OAuth settings.

* Default server address could/should be `https://<viewer-host>/server/`
* Other settings (branding, oauth) may be loaded from `https://<viewer-host>/config/`

See also https://github.com/dcs4cop/xcube/issues/437

**Comment by AliceBalfanz** [comment]
@forman , that would be great! I have a question though - how can we ensure that `https://<viewer-host>/config/` can stay private if needed?

**Comment by forman** [comment]
Closed by #170
