### ISSUE TITLE
imprint and user maual links broken

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#169]
Access to the imprint and user manual is not available anymore, although they are included into the build directory. 

![image](https://user-images.githubusercontent.com/23457217/116410750-5a7ff380-a835-11eb-9bba-e968df181db5.png)
![image](https://user-images.githubusercontent.com/23457217/116410793-65d31f00-a835-11eb-9294-5a56fcdd9464.png)

**Comment by forman** [comment]
This should be an issue on the web server end. Both files are in the final build.

**Comment by forman** [comment]
It is.
