### ISSUE TITLE
Switching the RGB button occasionally 

### ISSUE THREAD

**Issue by dzelge** [dcs4cop/xcube-viewer#173]
## Current behaviour

The following issue occurred when testing the cyanoalert service.  When switching the `RGB` button off occasionally the area covered RGB image stays white:

Before switching:
![image](https://user-images.githubusercontent.com/42441761/118495621-a8e12d80-b723-11eb-9f82-a5cd7bccc60c.png)

After swicthing:

![image](https://user-images.githubusercontent.com/42441761/118495578-9bc43e80-b723-11eb-93b3-016bbf89043a.png)

## Expected behaviour:

The RGB Image disappears entirely

**Comment by AliceBalfanz** [comment]
@dzelge After switching the RGB button of, you see the underlying variable, which in you case was one of the RGB bands. Closing the issue, feel free to reopen in case you think this is still a problem.
