### ISSUE TITLE
Several Base Maps are not working

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#197]
While changing the base map I noticed, that the following base maps are not working: 

- Stamen (all)
- Mapbox (all)
- OpenStreetMap : OSM Black & White , OSM Landscape

**Comment by forman** [comment]
@AliceBalfanz if your time allows for, you can outcomment or fix the ones not working in [here](https://github.com/dcs4cop/xcube-viewer/blob/master/src/resources/maps.json).
