### ISSUE TITLE
viewer reloads every 5 min

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#256]
When an xcube viewer is configured with user login and one is logged in, the viewer keeps reloading the data every 5 min. 
This is very inconvenient as it resets the image view to the default.
To see behaviour check out our bc-demo viewer https://bc-viewer.brockmann-consult.de/ and log in.

**Comment by forman** [comment]
Ok, issue is caused by automatic token refresh. Should be easy to fix.
