### ISSUE TITLE
Un-branded light theme to show time series axis description

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#268]
The un-branded light theme of the xcube-viewer seeems to have default settings that do not show the axis description of the time series plot. 

![image](https://user-images.githubusercontent.com/23457217/220304913-750ca003-2f13-4211-8953-1a3c619f2a28.png)

The default viewer styles need to be fixed in order to show the descriptions.

**Comment by forman** [comment]
Weird, how can I reproduce that?

**Comment by jorritscholze** [comment]
<img width="755" alt="viewer-NB" src="https://user-images.githubusercontent.com/28300787/228802693-d8691d41-04b7-4edd-8dc6-d59afc9cdaaa.png">

Same thing happens in the JBN viewer. The label and ticks of the timeseries axes are not visible.

**Comment by AliceBalfanz** [comment]
> Weird, how can I reproduce that?

You can reproduce with removing any viewer config (e.g. move away the config folder from your xcube-viewer repository) and then launch the viewer with a server. You will see an unbranded viewer and when plotting a time series, you will notice lacking graph description.

![image](https://user-images.githubusercontent.com/23457217/231158529-0c29a32d-8903-4569-909d-39ac20866230.png)
