### ISSUE TITLE
viewer does not zoom to selected place point location

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#52]
When choosing a place from the list of locations provided for a specific data cube, the viewer does not zoom to the selected one. However, when selecting a polygon, the zoom is working. 

In order to reproduce the bug:
Go to the [cyanoalert viewer](http://viewer.cyanoalert.com/). And from the drop-down menue `Places` select `Sverige selected bathing sites`. Then klick on any of the places provided in the drop-down menue `Place`.  The issue exists for the other data cubes with point location data as well.

**Comment by dzelge** [comment]
Bug found and fixed. 

The Viewer sets now a bounding box of 1000m around a point when zooming in to that point. Will open an issue around this as it might cause issues. Should be configurable.
