### ISSUE TITLE
Zooming to Points when selecting a Place

### ISSUE THREAD

**Issue by dzelge** [dcs4cop/xcube-viewer#54]
**Is your feature request related to a problem? Please describe.**
When selecting a Place the system zooms to that selected geometry. If that geometry is a point
the extent the system zooms to is very small. IF PR #53 is accepted than the system will
use a bounding box of 1km/0.01degree around that point.

**Describe the solution you'd like**
Make the extend around a point geometry configurable

**Describe alternatives you've considered**
Creating a bounding box of 1km/0.01deg around a point. 

**Additional context**
The issue is that you need to consider the projection of the map and the extent of the map. If teh extent of the map is very small or the poitns a very close together, a bounding box of 1km might be too much.

**Comment by forman** [comment]
I suggest not zooming in at all, but just center the view at the point.

**Comment by forman** [comment]
Working on this, because users find it confusing to zoom deeply into the map when a point is selected.

**Comment by forman** [comment]
> I suggest not zooming in at all, but just center the view at the point.

This is the current implementation, which is sub-optimal.

New suggestion: Center view on selected point. Then compute new zoom level from selected dataset's bounding box, e.g. from 1/10th of its max dimension. If that is close to or less than current zoom level, do nothing. Otherwise zoom in.

**Comment by forman** [comment]
Implemented as suggested above in 0.2.0
