### ISSUE TITLE
Use custom value ticks in legend for SNAP custom colormaps

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#55]
When using a custom SNAP colormap file for mapping a variable, the legend is not displayed with the predefined value ticks in the viewer. xcube serve has code for setting custom ticks, but this is not used by the viewer for displaying the legend: 
![image](https://user-images.githubusercontent.com/23457217/60894537-323f9300-a263-11e9-9757-8cb2e873d922.png)
This is the legend as it is:
![image](https://user-images.githubusercontent.com/23457217/60894636-5d29e700-a263-11e9-8a52-2e7993e1d09e.png)

Expected would be ticks along the colormap legend at specific colors with predefined values.

**EDIT**

To be fixed in combination with dcs4cop/xcube#84

**Comment by forman** [comment]
Fix in combination with https://github.com/dcs4cop/xcube/issues/84

**Comment by forman** [comment]
I think we can close this after our meeting with Carole and Kerstin, ok @AliceBalfanz?

**Comment by AliceBalfanz** [comment]
ok :)
