### ISSUE TITLE
Ease selection of exact time

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#58]
A calender for selecting the time stamp for which one wants to view the data would be very helpful. 
At the moment one can only push the play button and pause at the correct moment or try to select it from the time slider. 

![grafik](https://user-images.githubusercontent.com/23457217/61126485-d700e100-a4ac-11e9-821b-02ea0f94a94e.png)

Both approaches are difficult, to get the correct date right away. 

Besides a calender view, another possibility would be to allow the user to step one time stamp forward or one backwards, in order to get to the desired date. Maybe both possibilities could be implemented and not just one of them?

**Comment by forman** [comment]
Should be addressed in combination with #23, so we can indicate whether there is data on a certain date.

**Comment by forman** [comment]
There is already a branch for this issue: forman-45-new_time_controls

**Comment by forman** [comment]
https://material-ui.com/de/components/pickers/

**Comment by forman** [comment]
Done.
