### ISSUE TITLE
Viewer not displayed in Internet Explorer

### ISSUE THREAD

**Issue by clebreton** [dcs4cop/xcube-viewer#59]
The address is resolved but nothing is displayed. JavaScript and Flash Player are both enabled.
This is a problem for people in federal institutes who might not have the choice to use another browser

**Comment by AliceBalfanz** [comment]
Setting labels based on Caroles suggestion.

**Comment by dzelge** [comment]
IE and Edge do not support the Promise method 'finally'.

![grafik](https://user-images.githubusercontent.com/42441761/62467396-f7624980-b793-11e9-8417-bb2320682771.png)

**Comment by dzelge** [comment]
Adding the dependency fetch-bluebird and loading it using something like the following
whemn a Promise is returned seems to do the trick:

```
if(typeof (new Promise(()=>1).finally) === "undefined") {
    require('fetch-bluebird');
}
```

![grafik](https://user-images.githubusercontent.com/42441761/62468470-6e98dd00-b796-11e9-9bc5-dea6199e5a16.png)

**Comment by forman** [comment]
Please let's discuss possible solutions beforehand.
I don't like adding new dependencies, if there can be other workarounds, e.g. read https://stackoverflow.com/questions/35999072/what-is-the-equivalent-of-bluebird-promise-finally-in-native-es6-promises

**Comment by forman** [comment]
@dzelge, please close after testing

**Comment by dzelge** [comment]
Geht jetzt soweit man sehen kann.

![grafik](https://user-images.githubusercontent.com/42441761/62603929-34931c80-b8f7-11e9-9617-0d25ce5adab0.png)

**Comment by forman** [comment]
Ok, now please merge change into `master_cyanoalert` and `master_dcs4cop`.

**Comment by dzelge** [comment]
Done. @AliceBalfanz @forman Wer updated das auf den life servern?

**Comment by forman** [comment]
Alicja

**Comment by dzelge** [comment]
IE still fails with message: "Das Objekt unterstützt die Eigenschaft oder Methode "findIndex" nicht"

![grafik](https://user-images.githubusercontent.com/42441761/64950973-ffc29f80-d87c-11e9-8bd9-52b93bc8466d.png)

**Comment by forman** [comment]
IE? OMG. I'm actually against supporting such outdated browsers. After fixing this, we will likely see other issues too.

**Comment by dzelge** [comment]
I agree. But that needs to be communicated somehow. In addition, I think this will be hard to fix. 

 

------------------------

Helge

Brockmann Consult

 

Von: Norman Fomferra <notifications@github.com> 
Gesendet: Montag, 16. September 2019 13:46
An: dcs4cop/xcube-viewer <xcube-viewer@noreply.github.com>
Cc: Helge Dzierzon <helge.dzierzon@brockmann-consult.de>; State change <state_change@noreply.github.com>
Betreff: Re: [dcs4cop/xcube-viewer] Viewer not displayed in Internet Explorer or Microsoft Edge (#59)

 

IE? OMG. I'm actually against supporting such outdated browsers. After fixing this, we will likely see other issues too.

**Comment by forman** [comment]
Won't fix for IE.
