### ISSUE TITLE
time series graph without line between points

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#62]
The current view of the time series graph is plotting a line between the point values: 
![grafik](https://user-images.githubusercontent.com/23457217/61639341-97e84200-ac9b-11e9-9d4e-8e5ac214e674.png)

It would be great to have the possibility to get the graph without the interpolated line between the points.

**Comment by forman** [comment]
There are a couple of settings that should be user-adjustable

- [ ] whether to connect points by line
- [ ] whether to show error bars
- [ ] whether to compute stdev yes/no
- [ ] auto-play speed / time interval in millis

Should build a settings dialog with sections for
* time-series chart style
* language selection
* server selection
