### ISSUE TITLE
Investigate shift of cells in viewer

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#64]
When displaing OLCI data from data cube in the viewer, the cells seem to be shifted and that they do not cover the expected region exactly. 
In case of this example, there should be no cells visible over land, because the varialble only is aplying for cells over water. 
![grafik](https://user-images.githubusercontent.com/23457217/61791199-9a70a600-ae19-11e9-90fd-607da647ba73.png)

The reason for this shift needs to be investigated.

**Comment by forman** [comment]
Closing this in favor of https://github.com/dcs4cop/xcube/issues/206
