### ISSUE TITLE
Map view zooms out when computingtime series

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#81]
When selecting the time series for a user point which is placed in a certain region, the viewer automatically zooms out to the whole world extent when showing the time series for the point. 

To reproduce, go to [http://viewer.cyanoalert.com/](http://viewer.cyanoalert.com/), select a point and then compute the time series for the point. 
![grafik](https://user-images.githubusercontent.com/23457217/64177957-cc394b80-ce60-11e9-9e68-4550565a74ea.png)

![grafik](https://user-images.githubusercontent.com/23457217/64178008-e410cf80-ce60-11e9-9f74-365b8d0c70db.png)

Expected behaviour is, that the viewer keeps the region of the data cube when selecting a time series.

**Comment by forman** [comment]
Oh no, my fault. It is a regression caused by #79.
