### ISSUE TITLE
Fix code vulnerabilities

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube-viewer#89]
Run 

    $ yarn audit

Fix all vulnerabilities found.

Starting point is to fix current GitHub security alerts, see https://github.com/dcs4cop/xcube-viewer/network/alerts

**Comment by dzelge** [comment]
this won't be easy. js-yaml for instance comes in through other dependencies. this is all versions that yarn list prints:
```
│  │  ├─ js-yaml@^3.13.1
│  ├─ js-yaml@3.13.1
│  ├─ js-yaml@^3.4.3
│  ├─ js-yaml@^3.7.0
├─ js-yaml@3.12.1
│  ├─ js-yaml@~3.7.0
│  ├─ js-yaml@3.7.0
│  ├─ js-yaml@^3.7.0
```

**Comment by forman** [comment]
Done.
