### ISSUE TITLE
Data shifted wrt to underlying map

### ISSUE THREAD

**Issue by gunbra32** [dcs4cop/xcube-viewer#90]
Data and OSM displayed in the data reveal a systematic shift, more specifically, the data is shifted westwards with respect to the underlying map from OSM (see screenshot below).

![image](https://user-images.githubusercontent.com/7138923/64521913-33d81680-d2f9-11e9-99cb-3198a005566e.png)

![image](https://user-images.githubusercontent.com/7138923/64522084-831e4700-d2f9-11e9-86f5-a28550601a12.png)

The issue occurs in land and ocean variables: 

![image](https://user-images.githubusercontent.com/7138923/64522233-d42e3b00-d2f9-11e9-9285-a754c76d48df.png)

**Comment by forman** [comment]
I believe, I have an explanation now: For the ESDL cube, xcube server reports an geographical extent of `lon1=-180, lat1=-89.75, lon2=180, lat2=89.75`. These are the values extracted from `lon_bnds` and `lat_bnds` of the cube. The latitudes don't look ok to me, they should be `lat1=-90, lat2=90`.

For the layer display, the image's spatial resolution is required. In xcube server, it is currently computed as `(lat2 - lat1) / image_height`. For an image of size 1440 x 720 this discrepancy sums up to one degree in longitude-direction.

**Comment by forman** [comment]
https://github.com/dcs4cop/xcube/blob/master/xcube/webapi/controllers/tiles.py#L260

**Comment by dzelge** [comment]
But the skew is in longitude direction.

**Comment by dzelge** [comment]
> I believe, I have an explanation now: For the ESDL cube, xcube server reports an geographical extent of `lon1=-180, lat1=-89.75, lon2=180, lat2=89.75`. These are the values extracted from `lon_bnds` and `lat_bnds` of the cube. The latitudes don't look ok to me, they should be `lat1=-90, lat2=90`.
 
And the reason for that is!:  The ESDC cubes have the lats in reversed order:

![grafik](https://user-images.githubusercontent.com/42441761/69122210-8a529580-0a9e-11ea-8e69-e716dd70723f.png)

![grafik](https://user-images.githubusercontent.com/42441761/69122253-a5bda080-0a9e-11ea-99c8-1d9425b6dbb9.png)

**Comment by dzelge** [comment]
I think, we also get into some numerical issues: the difference between the second element of lon and the first should be exactly ```0.08333``` not ```0.08332825```

![grafik](https://user-images.githubusercontent.com/42441761/69123421-9d1a9980-0aa1-11ea-8092-5ac65d7c47ed.png)

**Comment by dzelge** [comment]
Shall I open an issue? xcube shoud have reported both incidents above: 

![grafik](https://user-images.githubusercontent.com/42441761/69125239-a9085a80-0aa5-11ea-8d6c-f242298aec02.png)

**Comment by forman** [comment]
Yes, please!

**Comment by forman** [comment]
> But the skew is in longitude direction.

That doesn't matter, because the computed resolution is applied to both directions. Afaik, OpenLayers cannot have different x,y resolutions.

**Comment by forman** [comment]
Let's see if https://github.com/dcs4cop/xcube/issues/232 resolves the problem...

**Comment by forman** [comment]
Ok, `xcube` code is fine because it follows [CF Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#cell-boundaries):

> for an increasing coordinate, lat(1) > lat(0) implies latbnd(i,1) >= latbnd(i,0) for all i

which implies that

* for a **decreasing** coordinate, lat(1) **<** lat(0) implies latbnd(i,1) **<=** latbnd(i,0) for all i

According to this definition, the ESDL latitude bounds coordinate `lat_bnds` is wrongly filled.
