### ISSUE TITLE
Fix legend on dcs4cop_master branch

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#96]
Something happened to the dcs4cop legend ([dcs4cop viewer](https://dcs4cop-demo-viewer.obs-website.eu-de.otc.t-systems.com/)) 
![Screenshot from 2019-10-01 11-26-48](https://user-images.githubusercontent.com/23457217/65950454-64b1f400-e43e-11e9-8da9-ae0577d3359a.png)

It also completely disappears when making a time series:
![Screenshot from 2019-10-01 11-27-35](https://user-images.githubusercontent.com/23457217/65950562-96c35600-e43e-11e9-86c0-f6f909a2f7dd.png)

this build was created with the newest version of the dcs4cop_master branch.

**Comment by forman** [comment]
The only difference of `master` and `dcs4cop_master` is `config.ts`, which is ok. The problem must originate from server or the published data cubes.

**Comment by forman** [comment]
@AliceBalfanz , maybe the display ranges are invalid, e.g. min=max?

**Comment by AliceBalfanz** [comment]
I think, this will be fixed with the new release. When I use the dcs4cop config with the master branch, then I do not get the error anymore. Leaving the issue open, until tested with master_dcs4cop branch after it hast been updated to the sate of the master branch.

**Comment by AliceBalfanz** [comment]
This issue persist after deployment of dcs4cop serer with xcube v0.3.0 and xcube viewer v0.3.0. , it even got worse:

![Screenshot from 2019-11-25 08-00-26](https://user-images.githubusercontent.com/23457217/69519197-b025e180-0f59-11ea-8df6-2d75060e4eda.png)

![Screenshot from 2019-11-25 08-01-15](https://user-images.githubusercontent.com/23457217/69519231-cb90ec80-0f59-11ea-9176-e779f5974c2f.png)

This issue does not exist, when locally executing `yarn run start` on the master_dcs4cop branch. 

![image](https://user-images.githubusercontent.com/23457217/69519534-989b2880-0f5a-11ea-8e9f-74f902c1aee6.png)

![image](https://user-images.githubusercontent.com/23457217/69519587-b1a3d980-0f5a-11ea-9c1a-876f25f5d592.png)

It seems, that there is an error when generating the build directory which then is used for the webpage. 
I tried the following: 
1. deleted existing build directory locally 
2. deleted existing files coming from the build directory in the s3 bucket, where the information for the webpage is stored. 
3. did a fresh yarn build
4. moved content of build directory into bucket.

**Comment by forman** [comment]
Closing this, as it was related to deployment problems on OTC only. Please reopen, if problems persists, feel free to reopen.
